# Site settings
title: Johnny Phung - A journey of love and new beginnings
description: > # this means to ignore newlines until "baseurl:"
repository: johnnyphung/website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://johnnyphung.github.io" # the base hostname & protocol for your site
author: Copyright &copy; 2025 - Johnny Phung
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
